<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sentry DSN
    |--------------------------------------------------------------------------
    |
    | The DSN tells the SDK where to send events. It can be found in your
    | Sentry project settings under Client Keys (DSN).
    |
    */

    'dsn' => env('SENTRY_LARAVEL_DSN'),

    /*
    |--------------------------------------------------------------------------
    | Environment
    |--------------------------------------------------------------------------
    */

    'environment' => env('SENTRY_ENVIRONMENT', env('APP_ENV', 'production')),

    /*
    |--------------------------------------------------------------------------
    | Release
    |--------------------------------------------------------------------------
    */

    'release' => env('SENTRY_RELEASE'),

    /*
    |--------------------------------------------------------------------------
    | Before Send Callback
    |--------------------------------------------------------------------------
    |
    | Filter out events before they are sent to Sentry. Returning null drops
    | the event entirely. This prevents the intentional test exception
    | generated by `php artisan sentry:test` from creating noise in the
    | production issue tracker.
    |
    */

    'before_send' => function ($event, $hint) {
        $exception = $hint !== null && isset($hint->exception) ? $hint->exception : null;

        if (
            $exception instanceof \Exception &&
            $exception->getMessage() === 'This is a test exception sent from the Sentry Laravel SDK.'
        ) {
            return null;
        }

        return $event;
    },

];